apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: nkoppalafacilgo/facilgo-api:v0.0.1
          ports:
            - containerPort: 8000
          resources:
            limits:
              memory: 192Mi
              cpu: 150m
            requests:
              cpu: 100m
              memory: 100Mi
          env:
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: api-srv-config
                  key: NODE_ENV
            - name: DATABASE_PORT
              valueFrom:
                secretKeyRef:
                  name: api-srv-secret
                  key: DATABASE_PORT
            - name: DATABASE_POOL_MIN
              valueFrom:
                secretKeyRef:
                  name: api-srv-secret
                  key: DATABASE_POOL_MIN
            - name: DATABASE_POOL_MAX
              valueFrom:
                secretKeyRef:
                  name: api-srv-secret
                  key: DATABASE_POOL_MAX
            - name: AES_KEY
              valueFrom:
                secretKeyRef:
                  name: api-srv-secret
                  key: AES_KEY
            - name: AES_IV
              valueFrom:
                secretKeyRef:
                  name: api-srv-secret
                  key: AES_IV
